### ISSUE TITLE
Using with coc.nvim, wrong error message

### ISSUE THREAD

**Issue by kroyagis** [mattn/efm-langserver#10]
it's throwing `syntax error, unexpected keyword_end, expecting ')'` at beginning and end of each block in `eruby` files.

**Comment by mattn** [comment]
what you get with `echo 1 | erb -x -T - | ruby -c` ?

**Comment by kroyagis** [comment]
in zsh, I get `Syntax OK`, inside neovim I get `Not an editor command: era -x -T - | ruby -c`

**Comment by mattn** [comment]
Did you typo? `s/era/erb/` ?

**Comment by kroyagis** [comment]
No, I did type `echo 1 | erb -x -T - | ruby -c`

**Comment by mattn** [comment]
Could you please provide your config.yaml?

**Comment by kroyagis** [comment]
Thanks @mattn for looking into this. Here is my config.yml:
```
languages:
  eruby:
    lint-command: 'erb -x -T - | ruby -c'
    lint-stdin: true
    lint-offset: 1
    format-command: 'htmlbeautifier'

  vim:
    lint-command: 'vint -'
    lint-stdin: true

  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'
```
