### ISSUE TITLE
JSON not being formatted

### ISSUE THREAD

**Issue by jack828** [mattn/efm-langserver#109]
Hey, excellent work on this project. I've just replaced w0rp/ale with this and oh is it nice. Thank you!

However, I am having some issues when it comes to JSON.

This is a snippet of my config.yaml:

```yaml
tools:
  json-jq: &json-jq
    lint-command: 'jq'
    lint-stdin: true
    lint-ignore-exit-code: true
  json-prettier: &json-prettier
    format-command: 'prettier ${--tab-width:tabWidth} --parser json'

languages:
  json:
    - <<: *json-jq
    - <<: *json-prettier
```

Now, with that config loaded I can see lint errors just fine. However, if I attempt to use `:lua vim.lsp.buf.formatting()` it will format fine, however my shortcut `<leader>p` does nothing.

I have `<leader>p` setup with this block (yes, copied from some neovim/lua guide)

```lua
  if client.resolved_capabilities.document_formatting then
    buf_set_keymap("n", "<space>p", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
  elseif client.resolved_capabilities.document_range_formatting then
    buf_set_keymap("n", "<space>p", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)
  end
```

I have a json language server installed.

However I am totally unaware of _how_ this feature is set - is this something efm needs configuring for or is this a problem elsewhere?

Thanks again!
