### ISSUE TITLE
Require detect marker to run tool command

### ISSUE THREAD

**Issue by rockerBOO** [mattn/efm-langserver#112]
Thanks for making this great language server! 

One thing I wish I could do is add a detect marker requirement. This would make it possible to not run tools if a marker files or pattern was detected. These opinionated formatters can wreck havoc if done on projects that don't support them. 

Example:
Only run prettier if `.prettierrc` is detected. 
Only run stylua if `stylua.toml` is detected.

```yaml
 lua-stylua-format: &lua-stylua-format
      format-command: 'stylua -'
      format-stdin: true
      root-markers:
        - 'stylua.toml'
      require-markers:
        - 'stylua.toml'
```
```yaml
   prettier: &prettier
      format-command: 'prettier --stdin-filename ${INPUT}'
      format-stdin: true
      require-markers:
        - '.prettierrc'
        - '.prettierrc.json'
```

Alternative:

```yaml
 lua-stylua-format: &lua-stylua-format
      format-command: 'stylua -'
      format-stdin: true
      root-markers:
        - 'stylua.toml'
      require-marker: true
```

Also to note sometimes markers are found inside a main config file. Like prettier supports package.json `{ prettier: ...}` 

- https://prettier.io/docs/en/configuration.html
- https://github.com/JohnnyMorganz/StyLua#configuration
