### ISSUE TITLE
Trouble setting up MATLAB's mlint

### ISSUE THREAD

**Issue by ngmoviedo** [mattn/efm-langserver#120]
I've been trying to setup efm-langserver through Neovim's built-in LSO for linting MATLAB files. I've checked the implementations in [Neomake](https://github.com/neomake/neomake/blob/8805e1547424d165fa909604a370fe21663e89fb/autoload/neomake/makers/ft/matlab.vim) and [ALE](https://github.com/dense-analysis/ale/blob/f0887d3e6178482255f11aa378124aef3699245f/ale_linters/matlab/mlint.vim), which I've used before and both worked well.
These are the relevant lines of my failed attempt:
```
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    filetypes = {'matlab'},
    settings = {
        languages = {
            matlab = {
                lintCommand = 'mlint -id',
                lintStderr = true,
                lintStdin= false,
                lintFormats = {
                    [[%f:L %l (C %c): %m]],
                    [[%f:L %l (C %c-%*[0-9]): %m]],
                },
            },
        },
    },
}
```
They are not producing any visible result nor any error, though, and I'm unable to determine why. According to `:LSPInfo`, efm-langserver is correctly loaded and the only language server running.
To exemplify to output of `mlint -id`, I'll attach a random warning and error:
```
L 135 (C 5-9): SAGROW: The variable 'pesos' appears to change size on every loop iteration (within a script). Consider preallocating for speed.
L 165 (C 2): SYNER: Parse error at <EOL>: usage might be invalid MATLAB syntax.
```
I suppose there may be a misconfiguration on my part, so I'll be happy to accept any help or hint in the right direction.

**Comment by ngmoviedo** [comment]
I'm suspecting a similar issue to #89. An error in the log about lint for the LanguageID not being supported is present in my case too.  I've even tried setting other linter (`fish -n`) to no avail. I'll try setting up the yaml file as soon as I can to see if it works that way.

**Comment by ngmoviedo** [comment]
Switching to `config.yaml` has proven successful for both mlint and fish -n. There was a slight mistake on mlint's error formatting, but that still doesn't explain why it wasn't working at all via neovim's configuaration.
Anyway, it behaves as expected now, so I'll stick to this config. I'll keep looking into it on my free time to get it working without the yaml file.

**Comment by ngmoviedo** [comment]
I finally managed to achieve the configuration via neovim's LSP. Here it is:
```
-- Table of severities
local severity = {}
severity['0']='I'
severity['1']='W'
severity['2']='W'
severity['3']='E'

require "lspconfig".efm.setup {
    init_options = {
        documentFormatting = true,
        },
    settings = {
        rootMarkers = {".git/"},
        languages = {
            matlab = {
                {
                    lintCommand = "/usr/bin/mlint -severity",
                    lintStdin = false,
                    lintStderr = true,
                    lintIgnoreExitCode = true,
                    lintFormats = {
                        'L %l (C %c): ML%t: %m',
                        'L %l (C %c-%*[0-9]): ML%t: %m'
                    },
                    lintCategoryMap = severity,
                }
            },
        }
    },
    filetypes = {'matlab'},
}
```
And the equivalent `config.yaml`:
```
version: 2
log-file: /tmp/efm.log
log-level: 4
root-markers:
  - .git/

tools:
    mlint: &mlint
        lint-command: '/usr/bin/mlint -severity'
        lint-stdin: false
        lint-stderr: true
        lint-ignore-exit-code: true
        lint-formats:
            - 'L %l (C %c): ML%t: %m'
            - 'L %l (C %c-%*[0-9]): ML%t: %m'
        lint-category-map:
            0: I
            1: W
            2: W
            3: E

languages:
    matlab:
        - <<: *mlint
 ```
