### ISSUE TITLE
Input from only saved buffer is used in formatting

### ISSUE THREAD

**Issue by bradcush** [mattn/efm-langserver#121]
To quote my earlier message in an unrelated ticket, "Both async and sync formatting work fine for me except the input passed to prettier in this case is only what's been saved so running the formatting before save ends up replacing the entire buffer with and saving the file without any changes. Am I missing something to have the unsaved contents of the buffer used? My setup is a bit different but quite similar to the above, I'm just using a config file with efm instead." I've included part of my configuration below as it was mentioned by @lukas-reineke [in the previous ticket](https://github.com/mattn/efm-langserver/issues/88#issuecomment-829733933) it was likely a config issue.

## `lsp.lua`
``` lua
local on_attach = function(client, bufnr)
    local function keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local opts = {noremap = true, silent = true}

    -- Set some keybinds conditional on server capabilities
    if client.resolved_capabilities.document_formatting then
        keymap('n', '<leader>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)
        vim.api.nvim_exec([[
            augroup formatting
                autocmd!
                autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 500)
            augroup END
        ]], true)
    elseif client.resolved_capabilities.document_range_formatting then
        keymap('n', '<leader>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)
    end
end

nvim_lsp['tsserver'].setup {
    on_attach = function(client, bufnr)
        client.resolved_capabilities.document_formatting = false
        on_attach(client, bufnr)
    end
}

require'lspconfig'.efm.setup {
    on_attach = on_attach,
    init_options = {documentFormatting = true},
}
```

## `config.yaml`
``` yaml
version: 2
log-file: /tmp/efm.log
log-level: 1
root-markers:
  - .git/

tools:
  eslint: &eslint
    lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    format-stdin: true

  prettier: &prettier
    format-command: 'prettier'

  typescript:
    - <<: *eslint
    - <<: *prettier

  typescriptreact:
    - <<: *eslint
    - <<: *prettier

  typescript.tsx:
    - <<: *eslint
    - <<: *prettier
```

**Comment by amiralies** [comment]
I'm not sure about this but I think you have to use stdin formatting in prettier.
something like this
```yml
  prettier: &prettier
    format-command: 'prettier --stdin --stdin-filepath ${INPUT}'
    format-stdin: true

```

**Comment by bradcush** [comment]
Thanks for the help @amiralies, makes sense, this was in fact the case just without `--stdin` as a command line option. (`--stdin` doesn't seem to be a valid option for prettier, just eslint)
``` yaml
prettier: &prettier
    format-command: 'prettier --stdin-filepath ${INPUT}'
    format-stdin: true
```
