### ISSUE TITLE
Format elixir file with `mix format`

### ISSUE THREAD

**Issue by collegeimprovements** [mattn/efm-langserver#153]
Thanks a lot for this awesome plugin.

I'm trying to format `elixir` files with, the following config. 

```yaml
version: 2
log-level: 1

tools:
  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  mix_credo: &mix_credo
    lint-command: "mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
    root-markers:
      - mix.lock
      - mix.exs

  luafmt: &luafmt
    format-command: 'lua-format -i --no-keep-simple-function-one-line --no-break-after-operator --column-limit=150 --break-after-table-lb'
    format-stdin: true
  
  mix_format: &mix_format
    format-command: 'mix format'
    format-stdin: true

languages:
  elixir:
    - <<: *mix_credo
    - <<: *mix_format

```

But it doesn't seem to work.  
Here is the relevant config from `init.lua` file: 

```lua
require"lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    filetypes = {"lua", "elixir"},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            -- lua = {
            --     {
            --         formatCommand = "lua-format -i --no-keep-simple-function-one-line --no-break-after-operator --column-limit=150 --break-after-table-lb",
            --         formatStdin = true
            --     }
            -- }
        }
    }
}

```

However it's not working for elixir file but does work for lua files. 
Please help.
