### ISSUE TITLE
Prettier in efm-langserver seems to be ignoring my tsx files

### ISSUE THREAD

**Issue by Teajey** [mattn/efm-langserver#269]
efm-langserver seems to be ignoring my tsx files (running under Helix)
```
2023-11-22T18:13:25.954 helix_lsp::transport [INFO] efm-lsp-prettier -> {"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":true,"tabSize":2},"textDocument":{"uri":"file:///Users/<REDACTED>/Account.tsx"}},"id":1}
2023-11-22T18:13:25.955 helix_lsp::transport [INFO] efm-lsp-prettier <- {"id":1,"result":null,"jsonrpc":"2.0"}
2023-11-22T18:13:25.955 helix_lsp::transport [INFO] efm-lsp-prettier <- null
```

Here's my config
```toml
[language-server.efm-lsp-prettier]
command = "efm-langserver"
args = [ "-logfile", "efmlog", "-loglevel", "2" ]
[language-server.efm-lsp-prettier.config]
documentFormatting = true
[[language-server.efm-lsp-prettier.config.languages.typescript]]
formatCommand ="yarn workspace foo prettier --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.css]]
formatCommand ="yarn workspace foo prettier --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.scss]]
formatCommand ="yarn workspace foo prettier --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.html]]
formatCommand ="yarn workspace foo prettier --stdin-filepath ${INPUT}"
formatStdin = true
```

Formatting's working for all other languages listed. Is there a `[[language-server.efm-lsp-prettier.config.languages.tsx]]` section that I need to add? I tried it, but couldn't see any difference. 

Does efm-langserver treat `ts` and `tsx` as the same language, or seperate?

I tried to delve into efm-langserver's code
https://github.com/mattn/efm-langserver/blob/d3104d56a6b7af42d81852965c9778e5cf9ec6b9/langserver/lsp.go#L90
But couldn't figure out where it gets the `languageId` from if Helix doesn't send it, as seen in the above Helix logs.

I tried getting some more info with `args = [ "-logfile", "efmlog", "-loglevel", "2" ]`. The `efmlog` file is created, but stays empty...

I swear it was working fine for me last week and I didn't change anything, so I've no idea what I broke 😤

<details>
<summary>FWIW here's my language settings for Helix</summary>

```toml
[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server", "eslint" ]
auto-format = true


[[language]]
name = "tsx"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server", "eslint" ]
auto-format = true


[[language]]
name = "css"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-css-language-server" ]
auto-format = true


[[language]]
name = "scss"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-css-language-server" ]
auto-format = true


[[language]]
name = "html"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-html-language-server" ]
auto-format = true
```
</details>

**Comment by mattn** [comment]
Apart from the lsp configuration you need to put the efm-langserver configuration file config.yaml.

**Comment by Teajey** [comment]
I'm confused about why I also need a base configuration file when I have already configured Helix to send efm-langserver a configuration:
```yml
documentFormatting: true
languages:
  typescript:
    - formatCommand: yarn workspace foo prettier --stdin-filepath ${INPUT}
      formatStdin: true
  css:
    - formatCommand: yarn workspace foo prettier --stdin-filepath ${INPUT}
      formatStdin: true
  scss:
    - formatCommand: yarn workspace foo prettier --stdin-filepath ${INPUT}
      formatStdin: true
  html:
    - formatCommand: yarn workspace foo prettier --stdin-filepath ${INPUT}
      formatStdin: true
```

**Comment by Teajey** [comment]
I got it working. I added this at `$HOME/.config/efm-langserver/config.yaml`
```yml
version: 2
log-file: /Users/thomas/.logs/efm-langserver
log-level: 1
```
And found this in the logs:
```
2023/11/24 10:22:37 lint for LanguageID not supported: typescriptreact
2023/11/24 10:22:39 format for LanguageID not supported: typescriptreact
```
So I just needed to add this to my Helix config
```toml
[[language-server.efm-lsp-prettier.config.languages.typescriptreact]]
formatCommand ="yarn workspace iot-ex prettier --stdin-filepath ${INPUT}"
formatStdin = true
```
