### ISSUE TITLE
Help on python: darglint

### ISSUE THREAD

**Issue by aemonge** [mattn/efm-langserver#284]
I've tried the following, but I'm sure the lint options are not set correctly:

```
tools:
    python-darglint: &python-darglint
        lint-command: 'darglint -s numpy ${INPUT}'
        lint-stdin: false
        lint-formats:
            - '%f:%l:%t:%n: %m'
        lint-ignore-exit-code: true

languages:
    python:
        - <<: *python-darglint
```

Example output:
```
❯ darglint -s numpy /tmp/a.py
/tmp/a.py:example:4: DAR103:  ~a: expected int but was str
```

And error log:
```
   1 2024/08/08 14:20:23 lint for LanguageID not supported: python
```
