### ISSUE TITLE
ERROR: can not read configuration: yaml: line 13: did not find expected key

### ISSUE THREAD

**Issue by rafaelnp** [mattn/efm-langserver#40]
I have the following error when ttrying to use efm-langserver + cocn.vim + neovim on Arch Linux:

**can not read configuration: yaml: line 13: did not find expected key**

Version information:

- vim version: NVIM v0.4.3
- node version: v10.19.0
- coc.nvim version: 0.0.75-89c0c2380b
- term: xterm-256color
- platform: linux
- efm-langserver: v0.0.9 (**update: tested v0.0.10, same error**)

cocn.vim configuration (`~/.config/nvim/coc-settings.jso`):

```json
    // Viml, Yaml, Markdown
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["vim", "markdown", "yaml"]
    },
```

efm-langserver configuration (`~/.config/efm-langserver/config.yaml`):

```yaml
version: 2

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c /home/rnp/.config/markdownlint.json'
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'

   yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  vim:
    - <<: *vim-lint

  markdown:
    - <<: *markdown-markdownlint

  yaml:
    - <<: *yaml-yamllint
```
