### ISSUE TITLE
Anyone tried elixir for `mix credo` usage?

### ISSUE THREAD

**Issue by megalithic** [mattn/efm-langserver#62]
This is available in [ALE](https://github.com/dense-analysis/ale/blob/master/doc/ale-elixir.txt), but would love to surface this to nvim-lsp (neovim's built in LSP) using efm-langserver.

Anyone else run into this need?

**Comment by megalithic** [comment]
bump @mattn or @lukas-reineke any thoughts around this?

**Comment by mattn** [comment]
I'm not familier to elixir.

**Comment by lukas-reineke** [comment]
I don't know elixir either sorry, but I don't see why it wouldn't work.
This looks like the relevant file in ALE, https://github.com/dense-analysis/ale/blob/883978ece93bd19250d6d7e8b9659b48f23522e2/ale_linters/elixir/credo.vim

according to that, `format-command` should look something like `mix help credo && mix credo suggest --format=flycheck --read-from-stdin ${INPUT}`

**Comment by megalithic** [comment]
got it working!

```yaml
  mix_credo: &mix_credo
    lint-command: "mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - mix.lock
      - mix.exs
```
